
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for viid_ape
-- ----------------------------
DROP TABLE IF EXISTS `viid_ape`;
CREATE TABLE `viid_ape` (
  `ApeID` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '设备 ID',
  `Name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '名称',
  `Model` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '型号',
  `IPAddr` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT 'IP地址',
  `IPV6Addr` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT 'IPv6地址',
  `Port` int(6) DEFAULT NULL COMMENT '端口号',
  `Longitude` double(9,6) DEFAULT NULL COMMENT '经度',
  `Latitude` double(9,6) DEFAULT NULL COMMENT '纬度',
  `PlaceCode` varchar(6) COLLATE utf8_bin DEFAULT NULL COMMENT '安装地点行政区划代码',
  `Place` varchar(4) COLLATE utf8_bin DEFAULT NULL COMMENT '位置名',
  `OrgCode` varchar(12) COLLATE utf8_bin DEFAULT NULL COMMENT '管辖单位代码',
  `CapDirection` int(1) DEFAULT NULL COMMENT '车辆抓拍方向',
  `MonitorDirection` int(2) DEFAULT NULL COMMENT '监视方向',
  `MonitorAreaDesc` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '监视区域说明',
  `IsOnline` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否在线',
  `OwnerApsID` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '所属采集系统',
  `UserId` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户帐号',
  `Password` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '口令',
  PRIMARY KEY (`ApeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='采集设备表';

-- ----------------------------
-- Table structure for viid_aps
-- ----------------------------
DROP TABLE IF EXISTS `viid_aps`;
CREATE TABLE `viid_aps` (
  `ApsID` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '设备ID',
  `Name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '名称',
  `IPAddr` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT 'IP地址',
  `IPV6Addr` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT 'IPv6地址',
  `Port` int(6) DEFAULT NULL COMMENT '端口号',
  `IsOnline` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否在线',
  PRIMARY KEY (`ApsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='采集系统表';

-- ----------------------------
-- Table structure for viid_cascade_platform
-- ----------------------------
DROP TABLE IF EXISTS `viid_cascade_platform`;
CREATE TABLE `viid_cascade_platform` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `SystemID` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '平台ID',
  `Name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '平台名称',
  `IPAddr` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT 'IP地址',
  `Port` varchar(6) COLLATE utf8_bin DEFAULT NULL COMMENT '端口',
  `IsOnline` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否在线',
  `LastOnlineTime` datetime DEFAULT NULL COMMENT '最后在线时间',
  `Type` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '级联平台类型（0上级 1下级）',
  `UserId` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `Password` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '密码',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='级联信息表';

-- ----------------------------
-- Table structure for viid_face
-- ----------------------------
DROP TABLE IF EXISTS `viid_face`;
CREATE TABLE `viid_face` (
  `FaceID` varchar(255) COLLATE utf8_bin NOT NULL,
  `InfoKind` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SourceID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DeviceID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LeftTopX` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LeftTopY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RightBtmX` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RightBtmY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LocationMarkTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FaceAppearTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FaceDisAppearTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IDType` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IDNumber` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `UsedName` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Alias` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `GenderCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AgeUpLimit` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AgeLowerLimit` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EthicCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NationalityCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NativeCityCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ResidenceAdminDivision` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ChineseAccentCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `JobCategory` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AccompanyNumber` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SkinColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HairStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HairColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FaceStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FacialFeature` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PhysicalFeature` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RespiratorColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CapStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CapColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `GlassStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `GlassColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsDriver` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsForeigner` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PassportType` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ImmigrantTypeCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsSuspectedTerrorist` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SuspectedTerroristNumber` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsCriminalInvolved` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CriminalInvolvedSpecilisationCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BodySpeciallMark` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CrimeMethod` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CrimeCharacterCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EscapedCriminalNumber` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsDetainees` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DetentionHouseCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DetaineesIdentity` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DetaineesSpecialIdentity` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `MemberTypeCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsVictim` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VictimType` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `InjuredDegree` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CorpseConditionCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsSuspiciousPerson` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Attitude` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Similaritydegree` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EyebrowStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NoseStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `MustacheStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LipStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `WrinklePouch` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AcneStain` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FreckleBirthmark` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ScarDimple` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `OtherFeature` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SubImageList` text COLLATE utf8_bin,
  PRIMARY KEY (`FaceID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
-- Table structure for viid_motor_vehicle
-- ----------------------------
DROP TABLE IF EXISTS `viid_motor_vehicle`;
CREATE TABLE `viid_motor_vehicle` (
  `MotorVehicleID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `InfoKind` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SourceID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TollgateID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DeviceID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `StorageUrl1` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `StorageUrl2` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `StorageUrl3` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `StorageUrl4` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `StorageUrl5` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LeftTopX` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LeftTopY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RightBtmX` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RightBtmY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `MarkTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AppearTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DisappearTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LaneNo` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HasPlate` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateClass` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateNo` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateNoAttach` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateDescribe` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsDecked` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsAltered` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsCovered` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Speed` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Direction` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DrivingStatusCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `UsingPropertiesCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleClass` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleBrand` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleModel` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleStyles` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleLength` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleWidth` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleHeight` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleColorDepth` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleHood` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleTrunk` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleWheel` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `WheelPrintedPattern` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleWindow` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleRoof` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleDoor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SideOfVehicle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CarOfVehicle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RearviewMirror` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleChassis` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleShielding` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FilmColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsModified` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HitMarkInfo` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleBodyDesc` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleFrontItem` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DescOfFrontItem` text COLLATE utf8_bin,
  `VehicleRearItem` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DescOfRearItem` text COLLATE utf8_bin,
  `NumOfPassenger` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PassTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NameOfPassedRoad` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsSuspicious` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Sunvisor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SafetyBelt` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Calling` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateReliability` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateCharReliability` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BrandReliability` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SubImageList` text COLLATE utf8_bin
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
-- Table structure for viid_non_motor_vehicle
-- ----------------------------
DROP TABLE IF EXISTS `viid_non_motor_vehicle`;
CREATE TABLE `viid_non_motor_vehicle` (
  `NonMotorVehicleID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `InfoKind` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SourceID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DeviceID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LeftTopX` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LeftTopY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RightBtmX` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RightBtmY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `MarkTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AppearTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DisappearTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HasPlate` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateClass` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateNo` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateNoAttach` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PlateDescribe` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsDecked` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsAltered` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsCovered` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Speed` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Direction` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DrivingStatusCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `UsingPropertiesCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleBrand` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleType` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleLength` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleWidth` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleHeight` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleHood` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleTrunk` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleWheel` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `WheelPrintedPattern` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleWindow` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleRoof` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleDoor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SideOfVehicle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CarOfVehicle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RearviewMirror` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleChassis` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VehicleShielding` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FilmColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsModified` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SubImageList` text COLLATE utf8_bin
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
-- Table structure for viid_person
-- ----------------------------
DROP TABLE IF EXISTS `viid_person`;
CREATE TABLE `viid_person` (
  `PersonID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `InfoKind` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SourceID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DeviceID` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LeftTopX` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LeftTopY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RightBtmX` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RightBtmY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LocationMarkTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PersonAppearTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PersonDisAppearTime` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IDType` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IDNumber` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `UsedName` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Alias` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `GenderCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AgeUpLimit` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AgeLowerLimit` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EthicCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NationalityCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NativeCityCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ResidenceAdminDivision` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ChineseAccentCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PersonOrg` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `JobCategory` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AccompanyNumber` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HeightUpLimit` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HeightLowerLimit` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BodyType` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SkinColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HairStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HairColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Gesture` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Status` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FaceStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `FacialFeature` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PhysicalFeature` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BodyFeature` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HabitualMovement` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Behavior` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BehaviorDescription` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `Appendant` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `AppendantDescription` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `UmbrellaColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `RespiratorColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CapStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CapColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `GlassStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `GlassColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ScarfColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BagStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BagColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CoatStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CoatLength` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CoatColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TrousersStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TrousersColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TrousersLen` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ShoesStyle` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ShoesColor` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsDriver` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsForeigner` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PassportType` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ImmigrantTypeCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsSuspectedTerrorist` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SuspectedTerroristNumber` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsCriminalInvolved` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CriminalInvolvedSpecilisationCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BodySpeciallMark` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CrimeMethod` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CrimeCharacterCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EscapedCriminalNumber` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsDetainees` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DetentionHouseCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DetaineesIdentity` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DetaineesSpecialIdentity` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `MemberTypeCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsVictim` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VictimType` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `InjuredDegree` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CorpseConditionCode` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IsSuspiciousPerson` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SubImageList` text COLLATE utf8_bin
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
-- Table structure for viid_subscribe
-- ----------------------------
DROP TABLE IF EXISTS `viid_subscribe`;
CREATE TABLE `viid_subscribe` (
  `SubscribeID` varchar(40) COLLATE utf8_bin NOT NULL COMMENT '订阅标识符',
  `Title` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '订阅的主题和目标',
  `SubscribeDetail` varchar(2) COLLATE utf8_bin DEFAULT NULL COMMENT '订阅类别',
  `ResourceURI` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '订阅资源路径',
  `ApplicantName` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '申请人',
  `ApplicantOrg` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '申请单位',
  `BeginTime` varchar(15) COLLATE utf8_bin DEFAULT NULL COMMENT '开始时间',
  `EndTime` varchar(15) COLLATE utf8_bin DEFAULT NULL COMMENT '结束时间',
  `ReceiveAddr` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '信息接收地址',
  `ReportInterval` int(5) DEFAULT NULL COMMENT '信息上报间隔时间',
  `Reason` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '理由',
  `OperateType` varchar(5) COLLATE utf8_bin DEFAULT NULL COMMENT '操作类型',
  `SubscribeStatus` varchar(5) COLLATE utf8_bin DEFAULT NULL COMMENT '订阅执行状态',
  `SubscribeCancOrg` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '订阅取消单位',
  `SubscribeCancelPerson` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '订阅取消人',
  `CancelTime` datetime DEFAULT NULL COMMENT '取消时间',
  `CancelReason` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '取消原因',
  `SubscribeType` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '0 订阅上级 1被订阅',
  `ApprovalStatus` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '审批状态',
  `ApprovalUser` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '审批人',
  `ApprovalTime` datetime DEFAULT NULL COMMENT '审批时间',
  `ResultImageDeclare` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '返回结果图片约定\n-1 不要图片\r\n其 他 取 值 参 照 GA/T 1400.3-2017 中 Imagetype的定义：\r\n01 车辆大图\r\n02 车牌彩色小图\r\n03 车牌二值化图\r\n04 驾驶员面部特征图\r\n05 副驾驶面部特征图\r\n06 车标\r\n07 违章合成图\r\n08 过车合成图\r\n09 车辆特写图\r\n10 人员图\r\n11 人脸图\r\n12 非机动车图\r\n13 物品图\r\n14 场景图\r\n100 一般图片',
  `ResultFeatureDeclare` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '返回结果特征值约定\n-1 不要特征值\r\n1 需要返回特征值',
  `TabID` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '订阅分类标签标识',
  `SubscriberSendOrgID` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '订阅发起方ID',
  `SubscriberRecoverOrgID` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '被订阅方ID',
  `ResourceClass` int(2) DEFAULT NULL COMMENT '订阅资源类别\n订阅时必选， 指定订阅的 资源类别。\n0-卡口\n1-设备\n2-采集内容\n3-案件\n4-视图库\n5-行政区划\n',
  PRIMARY KEY (`SubscribeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

SET FOREIGN_KEY_CHECKS = 1;
